In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('dataset.csv')

In [4]:
df.head()

,id,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,Male,24.443011,1.699998,81.669950,yes,yes,2.000000,2.983297,Sometimes,no,2.763573,no,0.000000,0.976473,Sometimes,Public_Transportation,Overweight_Level_II
1,1,Female,18.000000,1.560000,57.000000,yes,yes,2.000000,3.000000,Frequently,no,2.000000,no,1.000000,1.000000,no,Automobile,Normal_Weight
2,2,Female,18.000000,1.711460,50.165754,yes,yes,1.880534,1.411685,Sometimes,no,1.910378,no,0.866045,1.673584,no,Public_Transportation,Insufficient_Weight
3,3,Female,20.952737,1.710730,131.274851,yes,yes,3.000000,3.000000,Sometimes,no,1.674061,no,1.467863,0.780199,Sometimes,Public_Transportation,Obesity_Type_III
4,4,Male,31.641081,1.914186,93.798055,yes,yes,2.679664,1.971472,Sometimes,no,1.979848,no,1.967973,0.931721,Sometimes,Public_Transportation,Overweight_Level_II

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              20758 non-null  int64
 1   Gender                          20758 non-null  str
 2   Age                             20758 non-null  float64
 3   Height                          20758 non-null  float64
 4   Weight                          20758 non-null  float64
 5   family_history_with_overweight  20758 non-null  str
 6   FAVC                            20758 non-null  str
 7   FCVC                            20758 non-null  float64
 8   NCP                             20758 non-null  float64
 9   CAEC                            20758 non-null  str
 10  SMOKE                           20758 non-null  str
 11  CH2O                            20758 non-null  float64
 12  SCC                             20758 non-null  str
 13  FAF                             20758 non-null  float64
 14  TUE                             20758 non-null  float64
 15  CALC                            20758 non-null  str
 16  MTRANS                          20758 non-null  str
 17  NObeyesdad                      20758 non-null  str
dtypes: float64(8), int64(1), str(9)
memory usage: 2.9 MB

In [6]:
df.describe()

,id,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,20758.00000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000
mean,10378.50000,23.841804,1.700245,87.887768,2.445908,2.761332,2.029418,0.981747,0.616756
std,5992.46278,5.688072,0.087312,26.379443,0.533218,0.705375,0.608467,0.838302,0.602113
min,0.00000,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,5189.25000,20.000000,1.631856,66.000000,2.000000,3.000000,1.792022,0.008013,0.000000
50%,10378.50000,22.815416,1.700000,84.064875,2.393837,3.000000,2.000000,1.000000,0.573887
75%,15567.75000,26.000000,1.762887,111.600553,3.000000,3.000000,2.549617,1.587406,1.000000
max,20757.00000,61.000000,1.975663,165.057269,3.000000,4.000000,3.000000,3.000000,2.000000

In [7]:
df.columns()

TypeError: 'Index' object is not callable

In [8]:
df.columns

Index(['id', 'Gender', 'Age', 'Height', 'Weight',
       'family_history_with_overweight', 'FAVC', 'FCVC', 'NCP', 'CAEC',
       'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE', 'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='str')

In [ ]:
df.isnull().sum()   # if there is any missing or empty cell

id                                0
Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [11]:
df.select_dtypes(include='object').columns #   .select_dtypes will chose whatever data type is told to it , as int , float , object for string then we typee .columns which means give me only name of the columns only
## this is done to convert the string columns to some no, or parametrs

C:\Users\sanup\AppData\Local\Temp\ipykernel_21148\109623881.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object').columns #   .select_dtypes will chose whatever data type is told to it , as int , float , object for string then we typee .columns which means give me only name of the columns only

Index(['Gender', 'family_history_with_overweight', 'FAVC', 'CAEC', 'SMOKE',
       'SCC', 'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='str')

#  Encoding Starts from here which means converting the string columns to some no, or parametrs

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = {}                      # Creating a dictionary to store the the numbers. corresponding to the string values of the columns
for col in df.select_dtypes(include='object').columns:  # this loop will run for all the columns which are of type string or object
    le = LabelEncoder()                # creating an object of the label encoder class  
    df[col] = le.fit_transform(df[col])  # this will convert the string values of the column to some numbers and store it in the same column
    label_encoder[col] = le        # this will store the label encoder object in the dictionary with the column name as the key

C:\Users\sanup\AppData\Local\Temp\ipykernel_21148\1031021472.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object').columns:

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              20758 non-null  int64
 1   Gender                          20758 non-null  int64
 2   Age                             20758 non-null  float64
 3   Height                          20758 non-null  float64
 4   Weight                          20758 non-null  float64
 5   family_history_with_overweight  20758 non-null  int64
 6   FAVC                            20758 non-null  int64
 7   FCVC                            20758 non-null  float64
 8   NCP                             20758 non-null  float64
 9   CAEC                            20758 non-null  int64
 10  SMOKE                           20758 non-null  int64
 11  CH2O                            20758 non-null  float64
 12  SCC                             20758 non-null  int64
 13  FAF                             20758 non-null  float64
 14  TUE                             20758 non-null  float64
 15  CALC                            20758 non-null  int64
 16  MTRANS                          20758 non-null  int64
 17  NObeyesdad                      20758 non-null  int64
dtypes: float64(8), int64(10)
memory usage: 2.9 MB

In [ ]:
x= df.drop(['NObeyesdad','id'],axis = 1 )    # They remove teh index and target column fro the data training as tehy are not meant to be used for machine learning  
y = df['NObeyesdad']

In [20]:
print(x)
print(y)

       Gender        Age    Height      Weight  \
0           1  24.443011  1.699998   81.669950
1           0  18.000000  1.560000   57.000000
2           0  18.000000  1.711460   50.165754
3           0  20.952737  1.710730  131.274851
4           1  31.641081  1.914186   93.798055
...       ...        ...       ...         ...
20753       1  25.137087  1.766626  114.187096
20754       1  18.000000  1.710000   50.000000
20755       1  20.101026  1.819557  105.580491
20756       1  33.852953  1.700000   83.520113
20757       1  26.680376  1.816547  118.134898

       family_history_with_overweight  FAVC      FCVC       NCP  CAEC  SMOKE  \
0                                   1     1  2.000000  2.983297     2      0
1                                   1     1  2.000000  3.000000     1      0
2                                   1     1  1.880534  1.411685     2      0
3                                   1     1  3.000000  3.000000     2      0
4                                   1     1  2.679664  1.971472     2      0
...                               ...   ...       ...       ...   ...    ...
20753                               1     1  2.919584  3.000000     2      0
20754                               0     1  3.000000  4.000000     1      0
20755                               1     1  2.407817  3.000000     2      0
20756                               1     1  2.671238  1.971472     2      0
20757                               1     1  3.000000  3.000000     2      0

           CH2O  SCC       FAF       TUE  CALC  MTRANS
0      2.763573    0  0.000000  0.976473     1       3
1      2.000000    0  1.000000  1.000000     2       0
2      1.910378    0  0.866045  1.673584     2       3
3      1.674061    0  1.467863  0.780199     1       3
4      1.979848    0  1.967973  0.931721     1       3
...         ...  ...       ...       ...   ...     ...
20753  2.151809    0  1.330519  0.196680     1       3
20754  1.000000    0  2.000000  1.000000     1       3
20755  2.000000    0  1.158040  1.198439     2       3
20756  2.144838    0  0.000000  0.973834     2       0
20757  2.003563    0  0.684487  0.713823     1       3

[20758 rows x 16 columns]
0        6
1        1
2        0
3        4
4        6
        ..
20753    3
20754    0
20755    3
20756    6
20757    3
Name: NObeyesdad, Length: 20758, dtype: int64

 We Need to train Our Model and test it so we need to divide our data into test data and train data

In [21]:
from sklearn.model_selection import train_test_split

x_test , x_train , y_test , y_train = train_test_split(x,y,test_size = 0.2 , random_state = 42)

# Evaluation

In [22]:
accuracy_score(y_test , y_pred)

NameError: name 'accuracy_score' is not defined